// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfvovretlqyxvlmlyonv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmdm92cmV0bHF5eHZsbWx5b252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjY5NTksImV4cCI6MjA3MDEwMjk1OX0.ZGhbGh9e8viDUMQMUI2-QQLO5Tf1q1P4mUYD9nMNXGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});